### ISSUE TITLE
.gitingore

### ISSUE THREAD

**Issue by manelcaireta** [Pablo-Palma/altostratus-etl-data-pipeline#1]
This project's main `.gitignore` file is mispelled.

Remember to use `git status` before commiting to ensure you are not uploading sensible files.

Also there are standard `.gitignore` templates such as  [Python.gitignore](https://github.com/github/gitignore/blob/main/Python.gitignore).

**Comment by Pablo-Palma** [comment]
Thanks Manel, solved!
